### ISSUE TITLE
Selhání exportu redukovaného balíčku

### ISSUE THREAD

**Issue by kerschfilip** [LIBCAS/ARCLib#138]
Dobrý den,

narážím na problémy při exportu dat redukovaných balíčků. Nejsem si úplně jistý, zda se jedná o chybu aplikace nebo někde na mojí straně, prosím tedy o prozkoumání.

Pokoušel jsem se exportovat původní skeny (obsah složky Original_Tiff_LZW) z AIP s Autorským ID: 38bf6c3a-18cd-4342-8c48-b22c1901c8b7  
Export konfigurace byl následující: 
![image](https://user-images.githubusercontent.com/57805328/212012316-6645a427-61cb-483d-a8fa-beb805bcfdc2.png)

Výsledkem jsou skutečně vyexportované skeny, ale ne všechny. Status exportu - soubor `export` - má příponu `.failed`

Pokud z hromádky vyberu dva balíčky (např. 38bf6c3a-18cd-4342-8c48-b22c1901c8b7 a 013e5641-f967-46d6-bbbc-af2985418cde) a provedu export stejným způsobem, tak se mi k jednomu balíčku vyexportovala větší část skenů (ale zase ne všechny) a k druhému nic.  

V souboru `status.failed` se objevuje následující:
```
java.io.FileNotFoundException: /opt/arclib/fileStorage/prod1/prod1ex/fk/20230112091250/data_with_xml/463199e3-04c1-4b2f-929f-2bbbbf913c89/463199e3-04c1-4b2f-929f-2bbbbf913c89_xml_1.xml (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at cz.cas.lib.arclib.utils.ZipUtils.extractFile(ZipUtils.java:70)
	at cz.cas.lib.arclib.service.archivalStorage.ArchivalStorageResponseExtractor.extractAipAsFolderWithXmlsBySide(ArchivalStorageResponseExtractor.java:70)
	at cz.cas.lib.arclib.service.AipExportService.export(AipExportService.java:229)
	at cz.cas.lib.arclib.service.AipExportService.lambda$initiateExport$1(AipExportService.java:148)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) 
```

Napadlo mě tedy, že je možná špatně regex, ale stejně mě zaráží, že část dat se vyexportuje a část ne.   
Díky za pomoc!

**Comment by yantom** [comment]
Jednalo se o chybu exportu, již je opraveno,

**Comment by kerschfilip** [comment]
export dat redukovaných balíčků mi funguje správně, narážím ale na problém při exportu dat, která nechci redukovat, ale chci získat kompletní AIP.   
Postup:
- vytvoření vyhledávacího dotazu (testoval jsem na dotazu s názvem "český lid 2000" na testovacím prostředí)
- u vyhledávacího dotazu vyberu `Export výsledků vyhledávání` 
- v dialogovém okně nevybírám žádnou šablonu exportu, protože data nechci redukovat:
![arclib_export_fail](https://user-images.githubusercontent.com/57805328/234850098-2e3a3d93-5aa6-4036-80bd-2e6cacdc91b0.png)


export selže a v `export.failed` je:
```
java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:311)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:123)
	at cz.cas.lib.arclib.service.archivalStorage.ArchivalStorageResponseExtractor.extractAipAsFolderWithXmlsBySide(ArchivalStorageResponseExtractor.java:63)
	at cz.cas.lib.arclib.service.AipExportService.export(AipExportService.java:232)
	at cz.cas.lib.arclib.service.AipExportService.lambda$initiateExport$1(AipExportService.java:149)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) 
```

Díky za pomoc

**Comment by kerschfilip** [comment]
@yantom domnívám se, že tady ještě nějaký problém přetrvává. Při stejném postupu popsaném výše se mi při exportu na základě vyhledávacího dotazu (dotaz "český lid 2000" na testovacím prostředí) vyexportuje do workspace pouze první balíček, přestože dotazu odpovídají balíčky dva. Viz export prod1ex/fk/20240314115039/

Pokud data v exportu redukuji, pak se vyexportují správně data z obou balíčků viz export prod1ex/fk/20240314115101/

![image](https://github.com/LIBCAS/ARCLib/assets/57805328/ae0c1d2d-ef5e-4a18-9d64-3e809c268bbc)

**Comment by yantom** [comment]
Potvrzuji, jedná se o volání chybného endpointu z UI.

**Comment by yantom** [comment]
Oprava nasazena na TEST.
